FROM balenalib/rpi-raspbian

RUN apt-get update && \
	apt-get install --no-install-recommends -yq \
	python3 \
	python3-pip \
	libatlas-base-dev \
	libatomic1 \
	libfreetype6

RUN pip3 install \
	--no-cache-dir \
	grpcio==1.28.1 \
	grpcio-tools==1.28.1 \
	protobuf==3.11.3 \
	numpy==1.18.4 \
	six==1.14.0
